"""Initial migration

Revision ID: de961fac6f27
Revises:
Create Date: 2024-11-22 10:59:30.889117

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'de961fac6f27'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authz_permissions',
    sa.Column('id', sa.String(length=27), nullable=False),
    sa.Column('username', sa.String(length=500), nullable=False),
    sa.Column('permission', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_authz_permissions_id'),
        'authz_permissions',
        ['id'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authz_permissions_id'), table_name='authz_permissions')
    op.drop_table('authz_permissions')
    # ### end Alembic commands ###
